name: scouting_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.20.0+2

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.0.0
  collection: ^1.15.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.0
  faker: ^2.0.0
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_radar_chart: ^0.2.0
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  google_fonts: ^4.0.4
  graphql: ^5.1.1
  http: ^0.13.1
  image_picker: ^0.8.4+5
  orbit_standard_library: ^0.0.2
  percent_indicator: ^4.2.2
  progress_state_button: ^1.0.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  toggle_switch: ^2.0.1

dev_dependencies:
  args: ^2.3.0
  dotenv: ^4.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #- dev.env
    - lib/assets/
    # - lib\assets
    - lib/assets/logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/Wheely.png"
