// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBORfFaPQqITaPF3Pwlvv1kjmfo1KSfog',
    appId: '1:421711708113:web:24d3580f55e9c3d67eaaf0',
    messagingSenderId: '421711708113',
    projectId: 'pit-scouting-photos',
    authDomain: 'pit-scouting-photos.firebaseapp.com',
    storageBucket: 'pit-scouting-photos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_XHbV1I9GYlQfllWENW9d7JBQoLOpcY',
    appId: '1:421711708113:android:bc24bda7fb9ef0fb7eaaf0',
    messagingSenderId: '421711708113',
    projectId: 'pit-scouting-photos',
    storageBucket: 'pit-scouting-photos.appspot.com',
  );
}
