// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBM6Q77T4XiEfq7EkbKAqauD-UFXPs_OLg",
    appId: "1:345150904741:web:d13852b2577fcdeb88f04c",
    messagingSenderId: "345150904741",
    projectId: "orbit-scouting-2023",
    authDomain: "orbit-scouting-2023.firebaseapp.com",
    storageBucket: "orbit-scouting-2023.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAElPcuVitcB7bjANgpJN9dPFU1bxFsws0",
    appId: "1:345150904741:android:764800d67528fc2088f04c",
    messagingSenderId: "345150904741",
    projectId: "orbit-scouting-2023",
    storageBucket: "orbit-scouting-2023.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBPWfM80ANS-gHJi5uf1od-j4DTF4FUbV8",
    appId: "1:345150904741:ios:39d4f6253f0f039f88f04c",
    messagingSenderId: "345150904741",
    projectId: "orbit-scouting-2023",
    storageBucket: "orbit-scouting-2023.appspot.com",
    iosClientId:
        "345150904741-l2m72bss5a4bnvqlqv8rivj7n9qa33gk.apps.googleusercontent.com",
    iosBundleId: "com.example.ScoutingFrontend",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBPWfM80ANS-gHJi5uf1od-j4DTF4FUbV8",
    appId: "1:345150904741:ios:bd22c9c9dfc35e3e88f04c",
    messagingSenderId: "345150904741",
    projectId: "orbit-scouting-2023",
    storageBucket: "orbit-scouting-2023.appspot.com",
    iosClientId:
        "345150904741-uig7mjhpgh9ntbnarcfrl9grslt6dihu.apps.googleusercontent.com",
    iosBundleId: "com.example.scoutingFrontend",
  );
}
