// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCknAC_BlwUJQpX8c8_RTwKj4G1W3Y7QoI",
    appId: "1:670441461388:web:d06a4260ddb0351b634da9",
    messagingSenderId: "670441461388",
    projectId: "orbitscouting-85eb1",
    authDomain: "orbitscouting-85eb1.firebaseapp.com",
    storageBucket: "orbitscouting-85eb1.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCHQk9OYS9_pxOnXxPsArPwLIoJzZUgKuc",
    appId: "1:670441461388:android:0cebfef6732be95a634da9",
    messagingSenderId: "670441461388",
    projectId: "orbitscouting-85eb1",
    storageBucket: "orbitscouting-85eb1.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBT0C7tnEgySd24rwtEhIn6J0vrj5axlXk",
    appId: "1:670441461388:ios:d9ec418424dd8958634da9",
    messagingSenderId: "670441461388",
    projectId: "orbitscouting-85eb1",
    storageBucket: "orbitscouting-85eb1.appspot.com",
    iosClientId:
        "670441461388-gocua51juul6uk92k9rdtjlf0l82bv68.apps.googleusercontent.com",
    iosBundleId: "com.example.ScoutingFrontend",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBT0C7tnEgySd24rwtEhIn6J0vrj5axlXk",
    appId: "1:670441461388:ios:2968d10991d89adf634da9",
    messagingSenderId: "670441461388",
    projectId: "orbitscouting-85eb1",
    storageBucket: "orbitscouting-85eb1.appspot.com",
    iosClientId:
        "670441461388-aps6v3nm3geel0id2ldp7oa3un452u02.apps.googleusercontent.com",
    iosBundleId: "com.example.scoutingFrontend",
  );
}
